import React, { useState } from 'react';
import { Booking, HotelReservation, TransportReservation } from '../../types';
import { 
  Hotel, 
  Car, 
  Calendar, 
  MapPin, 
  Phone, 
  CheckCircle2, 
  Clock, 
  Edit3, 
  Search, 
  X, 
  Printer, 
  Luggage,
  ShieldCheck,
  User
} from 'lucide-react';

interface HotelTransportReservationProps {
  bookings: Booking[];
  onUpdateHotelReservation: (bookingId: string, hotel: HotelReservation) => void;
  onUpdateTransportReservation: (bookingId: string, transport: TransportReservation) => void;
  isOperatorView: boolean;
}

export const HotelTransportReservation: React.FC<HotelTransportReservationProps> = ({
  bookings,
  onUpdateHotelReservation,
  onUpdateTransportReservation,
  isOperatorView
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeSubTab, setActiveSubTab] = useState<'hotels' | 'transport'>('hotels');
  
  // Modal Editing State
  const [editingHotelBooking, setEditingHotelBooking] = useState<Booking | null>(null);
  const [hotelForm, setHotelForm] = useState<Partial<HotelReservation>>({});

  const [editingTransportBooking, setEditingTransportBooking] = useState<Booking | null>(null);
  const [transportForm, setTransportForm] = useState<Partial<TransportReservation>>({});

  const filteredBookings = bookings.filter((b) =>
    b.bookingRef.toLowerCase().includes(searchTerm.toLowerCase()) ||
    b.customer.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    b.tourTitle.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleOpenHotelModal = (b: Booking) => {
    setEditingHotelBooking(b);
    setHotelForm(b.hotelReservation || {
      id: `htl-${Date.now()}`,
      hotelName: 'Partner Hotel / Resort',
      roomType: 'Deluxe Room',
      checkInDate: b.travelDate,
      checkOutDate: b.travelDate,
      nights: 2,
      voucherCode: `HTL-VOUCH-${b.bookingRef.split('-')[2]}`,
      status: 'Confirmed',
      contactPhone: '+63 917 111 2222',
      notes: ''
    });
  };

  const handlePrintVoucher = (title: string, code: string, details: string) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>${title} - ${code}</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; color: #0f172a; max-width: 650px; margin: auto; }
            .badge { background: #0891b2; color: #fff; padding: 4px 12px; border-radius: 6px; font-size: 12px; font-weight: bold; }
            .header { border-bottom: 2px solid #0891b2; padding-bottom: 12px; margin-bottom: 20px; }
            .box { background: #f8fafc; border: 1px solid #cbd5e1; padding: 20px; border-radius: 12px; font-size: 14px; line-height: 1.6; }
            .footer { margin-top: 30px; font-size: 11px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <span class="badge">OFFICIAL TOUR OPERATOR VOUCHER PASS</span>
            <h2 style="margin: 8px 0 4px 0;">${title}</h2>
            <p style="margin:0; font-family: monospace; color: #0284c7; font-weight: bold;">Voucher Code: ${code}</p>
          </div>
          <div class="box">
            ${details}
          </div>
          <div class="footer">
            Generated by Holiday Travelers Travel and Tours Inc Platform • Verified & Confirmed
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  const handleSaveHotel = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingHotelBooking) return;
    const updatedHotel: HotelReservation = {
      id: hotelForm.id || `htl-${Date.now()}`,
      hotelName: hotelForm.hotelName || 'Partner Hotel',
      roomType: hotelForm.roomType || 'Standard Room',
      checkInDate: hotelForm.checkInDate || editingHotelBooking.travelDate,
      checkOutDate: hotelForm.checkOutDate || editingHotelBooking.travelDate,
      nights: Number(hotelForm.nights) || 1,
      voucherCode: hotelForm.voucherCode || `HTL-${Date.now()}`,
      status: (hotelForm.status as any) || 'Confirmed',
      contactPhone: hotelForm.contactPhone || '',
      notes: hotelForm.notes || ''
    };
    onUpdateHotelReservation(editingHotelBooking.id, updatedHotel);
    setEditingHotelBooking(null);
  };

  const handleOpenTransportModal = (b: Booking) => {
    setEditingTransportBooking(b);
    setTransportForm(b.transportReservation || {
      id: `trp-${Date.now()}`,
      vehicleType: 'Toyota Grandia Van',
      driverName: 'Assigned Driver',
      driverContact: '+63 918 333 4444',
      plateNumber: 'ABC-1234',
      pickupLocation: 'Airport Arrival',
      dropoffLocation: 'Hotel Lobby',
      pickupTime: '09:00 AM',
      status: 'Scheduled',
      notes: ''
    });
  };

  const handleSaveTransport = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingTransportBooking) return;
    const updatedTransport: TransportReservation = {
      id: transportForm.id || `trp-${Date.now()}`,
      vehicleType: transportForm.vehicleType || 'Van',
      driverName: transportForm.driverName || 'Driver',
      driverContact: transportForm.driverContact || '',
      plateNumber: transportForm.plateNumber || '',
      pickupLocation: transportForm.pickupLocation || 'Airport',
      dropoffLocation: transportForm.dropoffLocation || 'Hotel',
      pickupTime: transportForm.pickupTime || '09:00 AM',
      status: (transportForm.status as any) || 'Scheduled',
      notes: transportForm.notes || ''
    };
    onUpdateTransportReservation(editingTransportBooking.id, updatedTransport);
    setEditingTransportBooking(null);
  };

  return (
    <div className="space-y-6">
      {/* Submodule Banner */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none" />
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-cyan-400 text-xs font-semibold uppercase tracking-wider mb-1">
              <Hotel className="w-4 h-4" />
              <span>Submodule 04</span>
            </div>
            <h1 className="text-2xl font-bold text-white tracking-tight">
              Hotel & Transport Reservation
            </h1>
            <p className="text-sm text-slate-400 mt-1 max-w-2xl">
              Track accommodation check-in stays, issue hotel vouchers, and allocate vehicle transfers with driver dispatch info.
            </p>
          </div>

          <div className="flex items-center bg-slate-950 p-1 rounded-xl border border-slate-800">
            <button
              onClick={() => setActiveSubTab('hotels')}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition ${
                activeSubTab === 'hotels'
                  ? 'bg-cyan-600 text-white shadow'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <Hotel className="w-4 h-4" />
              <span>Hotel Stays</span>
            </button>
            <button
              onClick={() => setActiveSubTab('transport')}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition ${
                activeSubTab === 'transport'
                  ? 'bg-blue-600 text-white shadow'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <Car className="w-4 h-4" />
              <span>Transport Transfers</span>
            </button>
          </div>
        </div>

        {/* Search */}
        <div className="mt-5 pt-4 border-t border-slate-800">
          <div className="relative max-w-md">
            <Search className="w-4 h-4 absolute left-3.5 top-2.5 text-slate-400" />
            <input
              type="text"
              placeholder="Search reference, customer, or hotel name..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-10 pr-4 py-2 text-xs text-white focus:outline-none focus:border-cyan-500"
            />
          </div>
        </div>
      </div>

      {/* Tab Content 1: Hotel Reservations */}
      {activeSubTab === 'hotels' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {filteredBookings.map((b) => {
            const htl = b.hotelReservation;
            return (
              <div key={b.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-4">
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div>
                    <span className="font-mono text-xs font-bold text-cyan-400">{b.bookingRef}</span>
                    <h3 className="text-sm font-bold text-white">{b.customer.fullName}</h3>
                    <span className="text-[11px] text-slate-400">{b.tourTitle}</span>
                  </div>
                  {htl && (
                    <span className="px-2.5 py-1 rounded-md text-[10px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                      {htl.status}
                    </span>
                  )}
                </div>

                {htl ? (
                  <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2 text-xs text-slate-300">
                    <div className="flex items-center justify-between font-bold text-white">
                      <span>{htl.hotelName}</span>
                      <span className="text-cyan-400 font-mono text-[11px]">{htl.voucherCode}</span>
                    </div>
                    <div className="text-[11px] text-slate-400">Room Type: <strong className="text-slate-200">{htl.roomType}</strong> ({htl.nights} Nights)</div>
                    <div className="flex items-center gap-4 text-[11px]">
                      <div>Check-in: <strong className="text-white">{htl.checkInDate}</strong></div>
                      <div>Check-out: <strong className="text-white">{htl.checkOutDate}</strong></div>
                    </div>
                    <div className="text-[11px] text-slate-400">Front Desk: {htl.contactPhone}</div>
                    {htl.notes && <div className="text-[11px] text-amber-300 italic">Notes: {htl.notes}</div>}
                  </div>
                ) : (
                  <div className="p-4 bg-slate-950 border border-dashed border-slate-800 rounded-xl text-center text-xs text-slate-500">
                    No hotel accommodation allocated yet.
                  </div>
                )}

                <div className="flex items-center justify-between pt-2 border-t border-slate-800">
                  {htl ? (
                    <button
                      onClick={() => handlePrintVoucher(
                        `Hotel Pass: ${htl.hotelName}`,
                        htl.voucherCode,
                        `<strong>Guest:</strong> ${b.customer.fullName}<br/>
                        <strong>Tour:</strong> ${b.tourTitle} (${b.bookingRef})<br/>
                        <strong>Hotel:</strong> ${htl.hotelName}<br/>
                        <strong>Room Type:</strong> ${htl.roomType} (${htl.nights} Nights)<br/>
                        <strong>Check-In:</strong> ${htl.checkInDate} | <strong>Check-Out:</strong> ${htl.checkOutDate}<br/>
                        <strong>Front Desk Contact:</strong> ${htl.contactPhone}`
                      )}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 transition"
                    >
                      <Printer className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Print Pass</span>
                    </button>
                  ) : <div />}

                  {isOperatorView && (
                    <button
                      onClick={() => handleOpenHotelModal(b)}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-cyan-500/15 text-cyan-300 hover:bg-cyan-500/25 text-xs font-medium rounded-lg border border-cyan-500/30 transition"
                    >
                      <Edit3 className="w-3.5 h-3.5" />
                      <span>{htl ? 'Update Hotel' : 'Assign Hotel'}</span>
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Tab Content 2: Transport Reservations */}
      {activeSubTab === 'transport' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {filteredBookings.map((b) => {
            const trp = b.transportReservation;
            return (
              <div key={b.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-4">
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div>
                    <span className="font-mono text-xs font-bold text-cyan-400">{b.bookingRef}</span>
                    <h3 className="text-sm font-bold text-white">{b.customer.fullName}</h3>
                    <span className="text-[11px] text-slate-400">{b.tourTitle}</span>
                  </div>
                  {trp && (
                    <span className="px-2.5 py-1 rounded-md text-[10px] font-bold bg-blue-500/20 text-blue-300 border border-blue-500/30">
                      {trp.status}
                    </span>
                  )}
                </div>

                {trp ? (
                  <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2 text-xs text-slate-300">
                    <div className="flex items-center justify-between font-bold text-white">
                      <span>{trp.vehicleType}</span>
                      <span className="text-cyan-400 font-mono text-[11px]">{trp.plateNumber}</span>
                    </div>
                    <div className="text-[11px] text-slate-400">Driver: <strong className="text-slate-200">{trp.driverName}</strong> ({trp.driverContact})</div>
                    <div className="text-[11px] text-slate-400">Pickup: <strong className="text-white">{trp.pickupTime}</strong> at {trp.pickupLocation}</div>
                    <div className="text-[11px] text-slate-400">Dropoff: {trp.dropoffLocation}</div>
                  </div>
                ) : (
                  <div className="p-4 bg-slate-950 border border-dashed border-slate-800 rounded-xl text-center text-xs text-slate-500">
                    No vehicle transfer dispatched yet.
                  </div>
                )}

                {isOperatorView && (
                  <div className="flex justify-end">
                    <button
                      onClick={() => handleOpenTransportModal(b)}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-500/15 text-blue-300 hover:bg-blue-500/25 text-xs font-medium rounded-lg border border-blue-500/30 transition"
                    >
                      <Edit3 className="w-3.5 h-3.5" />
                      <span>{trp ? 'Update Dispatch Info' : 'Assign Vehicle'}</span>
                    </button>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Edit Hotel Modal */}
      {editingHotelBooking && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl max-w-lg w-full p-6 text-slate-100 shadow-2xl relative">
            <button
              onClick={() => setEditingHotelBooking(null)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white p-2 rounded-lg"
            >
              <X className="w-5 h-5" />
            </button>
            <h2 className="text-base font-bold text-white mb-4">
              Assign Hotel Reservation for {editingHotelBooking.bookingRef}
            </h2>

            <form onSubmit={handleSaveHotel} className="space-y-3">
              <div>
                <label className="text-xs font-medium text-slate-300 block mb-1">Hotel / Resort Name</label>
                <input
                  type="text"
                  required
                  value={hotelForm.hotelName || ''}
                  onChange={(e) => setHotelForm({ ...hotelForm, hotelName: e.target.value })}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Room Type</label>
                  <input
                    type="text"
                    required
                    value={hotelForm.roomType || ''}
                    onChange={(e) => setHotelForm({ ...hotelForm, roomType: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Voucher Code</label>
                  <input
                    type="text"
                    required
                    value={hotelForm.voucherCode || ''}
                    onChange={(e) => setHotelForm({ ...hotelForm, voucherCode: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Check-in Date</label>
                  <input
                    type="date"
                    value={hotelForm.checkInDate || ''}
                    onChange={(e) => setHotelForm({ ...hotelForm, checkInDate: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Check-out Date</label>
                  <input
                    type="date"
                    value={hotelForm.checkOutDate || ''}
                    onChange={(e) => setHotelForm({ ...hotelForm, checkOutDate: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
              </div>

              <div>
                <label className="text-xs font-medium text-slate-300 block mb-1">Frontdesk Phone</label>
                <input
                  type="text"
                  value={hotelForm.contactPhone || ''}
                  onChange={(e) => setHotelForm({ ...hotelForm, contactPhone: e.target.value })}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                />
              </div>

              <div className="pt-3 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setEditingHotelBooking(null)}
                  className="px-4 py-2 bg-slate-800 text-slate-200 text-xs rounded-xl"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-cyan-600 text-white text-xs font-bold rounded-xl"
                >
                  Save Voucher
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Transport Modal */}
      {editingTransportBooking && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl max-w-lg w-full p-6 text-slate-100 shadow-2xl relative">
            <button
              onClick={() => setEditingTransportBooking(null)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white p-2 rounded-lg"
            >
              <X className="w-5 h-5" />
            </button>
            <h2 className="text-base font-bold text-white mb-4">
              Assign Transport Dispatch for {editingTransportBooking.bookingRef}
            </h2>

            <form onSubmit={handleSaveTransport} className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Vehicle Type</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Coaster Van / Speedboat"
                    value={transportForm.vehicleType || ''}
                    onChange={(e) => setTransportForm({ ...transportForm, vehicleType: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Plate / Registration No.</label>
                  <input
                    type="text"
                    required
                    value={transportForm.plateNumber || ''}
                    onChange={(e) => setTransportForm({ ...transportForm, plateNumber: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Driver Name</label>
                  <input
                    type="text"
                    required
                    value={transportForm.driverName || ''}
                    onChange={(e) => setTransportForm({ ...transportForm, driverName: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Driver Contact No.</label>
                  <input
                    type="text"
                    required
                    value={transportForm.driverContact || ''}
                    onChange={(e) => setTransportForm({ ...transportForm, driverContact: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Pickup Location & Time</label>
                  <input
                    type="text"
                    required
                    value={transportForm.pickupLocation || ''}
                    onChange={(e) => setTransportForm({ ...transportForm, pickupLocation: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1">Dropoff Location</label>
                  <input
                    type="text"
                    required
                    value={transportForm.dropoffLocation || ''}
                    onChange={(e) => setTransportForm({ ...transportForm, dropoffLocation: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
              </div>

              <div className="pt-3 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setEditingTransportBooking(null)}
                  className="px-4 py-2 bg-slate-800 text-slate-200 text-xs rounded-xl"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-blue-600 text-white text-xs font-bold rounded-xl"
                >
                  Save Vehicle Dispatch
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
